### PR TITLE
Add unresolvable zabbix_server_hostname to /etc/hosts; Closes dj-wasabi/ansible-zabbix-web#65

### PR DESCRIPTION
**Pull request by kr4ut**
**Description of PR**
bi/ansible-zabbix-web#65

**Type of change**
Bugfix Pull Request

**Fixes an issue**
dj-wasabi/ansible-zabbix-web#65

### CODE REVIEW

**Comment by kr4ut** [comment]
@dj-wasabi Can you help me out here about requirements for dig lookup and ipaddr filter?
Don't fully understand the TravisCI setup here but thought should be the same like in zabbix-agent?

**Comment by dj-wasabi** [comment]
Hi @kr4ut 

Sorry for late reply, but the correct package is now installed with travis.

It fails now on this:

`fatal: [zabbix-web-pgsql-centos]: FAILED! => {"msg": "The conditional check 'not lookup('dig', 'qtype=A', zabbix_server_hostname ) | ipaddr' failed. The error was: An unhandled exception occurred while running the lookup plugin 'dig'. Error was a <class 'ansible.errors.AnsibleError'>, original message: The dig lookup requires the python 'dnspython' library and it is not installed\n\nThe error appears to have been in '/home/travis/build/dj-wasabi/ansible-zabbix-web/tasks/main.yml': line 56, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Add unresolvable $ZBX_SERVER as 127.0.1.1 to /etc/hosts\"\n  ^ here\n"}`

**Comment by hatifnatt** [comment]
Please also consider adding an option to disable this. Not everyone want to modify `hosts` file while installing Zabbix frontend.

**Comment by dj-wasabi** [comment]
True. Role should not be responsible for adding entries to a hosts file.

**Pull request closed without merging**
