### PR TITLE
Allow usage of php environment variables

### PR DESCRIPTION
**Pull request by toke**
Implements #12

### CODE REVIEW

**Comment by toke** [comment]
Not sure why the build failed but it more looks like a glitch while building the Docker infrastructure and is not related to the pull request itself. @dj-wasabi Any clues?

**Comment by dj-wasabi** [comment]
Hi @toke 

Yeah, ignore the error for now. Will provide a fix for that in a pr soon.
Are you able to add an example for using the `zabbix_web_env` as part of the `Examples of configuration`? Then immediately after that we can merge the PR.

Thank you!

**Comment by toke** [comment]
@dj-wasabi I tried it :-)

HTH,
Thomas

**Comment by dj-wasabi** [comment]
Thanks! 👍

**Comment by toke** [comment]
I found an issue with my approach. I will fix it ASAP.

**Comment by toke** [comment]
Fix in #15 Sorry for that.

**Pull request merged**
